### ISSUE TITLE
installation fails on raspberry pi

### ISSUE THREAD

**Issue by narduin** [YunoHost-Apps/rocketchat_ynh#38]
Hello !
First of all, thanks for the work you're doing devlopping this package.

I'm running into an error while installing the app (admin panel or cli, yunohost up to date).

```
Warning: W: Failed to fetch http://repo.mongodb.org/apt/debian/dists/jessie/mongodb-org/3.4/Release  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

Warning: W: Failed to fetch http://mirrordirector.raspbian.org/raspbian/dists/jessie-backports/main/binary-armhf/Packages  404  Not Found [IP: 93.93.128.193 80]

Warning: W: Failed to fetch http://mirrordirector.raspbian.org/raspbian/dists/jessie-backports/contrib/binary-armhf/Packages  404  Not Found [IP: 93.93.128.193 80]

Warning: W: Failed to fetch http://mirrordirector.raspbian.org/raspbian/dists/jessie-backports/non-free/binary-armhf/Packages  404  Not Found [IP: 93.93.128.193 80]

Warning: E: Some index files failed to download. They have been ignored, or old ones used instead.

Warning:   rocketchat's script has encountered an error. Its execution was cancelled.

Warning: Failed to stop rocketchat.service: Unit rocketchat.service not loaded.

Warning: Unknown service 'rocketchat'

Warning: sudo: mongo: command not found

Success! The SSOwat configuration has been generated

Error: Installation failed
```

Thanks for your help !

**Comment by selamanse** [comment]
Hi @patatus 

first of all - armhf installation is still experimentary for this package. This is due to missing test capability and also rocketchat&mongodb is not an recommended setup on one raspberry pi (I'm guessing you use pi).

seems like there is an issue with the armhf platform detection. The 3.4 mongodb repos are not compatible with armhf...so there is a "Failed to fetch" when the installation searches for an installation file for your platform.

I'm guessing that [this line](https://github.com/YunoHost-Apps/rocketchat_ynh/blob/master/scripts/_common.sh#L16) is expecting "armhf" but your pi is returning "binary-armhf"...so if you are quick with hacking this ....you could change [this line](https://github.com/YunoHost-Apps/rocketchat_ynh/blob/master/scripts/_common.sh#L16) in your local copy of _common.sh to test against "binary-armhf" ...I guess?

Can you also post your complete spec, os and installed versions of ynh?

**Comment by narduin** [comment]
Hey @selamanse !

I didn't know about the experimental/compatibility issues, thanks for clearing that up.
I am running yunohost 2.7.2 from a pi 3 on debian 8.0.

I tried to change the line you refered to to "binary-armhf" but no luck. Although this time I had some more warnings :
```
Warning: gpg: requesting key A15703C6 from hkp server keyserver.ubuntu.com
Warning: gpg: key A15703C6: "MongoDB 3.4 Release Signing Key <packaging@mongodb.com>" not changed
Warning: gpg: Total number processed: 1
Warning: gpg:              unchanged: 1
Warning: W: Failed to fetch http://repo.mongodb.org/apt/debian/dists/jessie/mongodb-org/3.4/Release  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)
```

**Comment by selamanse** [comment]
ok ... can you please run the command `dpkg --print-architecture` and post the output here?

**Comment by narduin** [comment]
The output is simply `armhf`.

If you think the problem is not worth debugging and I should wait for total support I understand =)

**Comment by selamanse** [comment]
@patatus thx. It's definitely worth documenting here. I marked this as a known issue/bug for armhf and will test as soon as I get my hands on a free pi.

**Comment by selamanse** [comment]
@patatus I'm sorry but I will close this issue. The setup here is still quite complicated and as stated out before: mongodb 3 support for raspi is still not there but in discussion (as far as I know). If you or anyone has more insight on this. feel free to reopen.
