### ISSUE TITLE
Can't use rocketchat electron app with rocketchat on yunohost

### ISSUE THREAD

**Issue by arthurzenika** [YunoHost-Apps/rocketchat_ynh#41]
When pointing to a rocketchat hosted on yunohost using rocketchat electron (https://github.com/RocketChat/Rocket.Chat.Electron/ - Desktop Client https://rocket.chat/download) it says "No valid server found at the URL"

I believe it is because the application looks for the URL at : domain/rocketchat/api/info and gets the yunohost SSO redirect. 

Would it be possible to have a whitelist on that URL to not redirect the SSO ? 

ps. and I believe the SSO is not working on this application, I had to reauthenticate when clicking on the RocketChat icon from yunohost.

**Comment by selamanse** [comment]
Hi @arthurlogilab, thanks for testing the desktop client. Currently SSO has to be disabled for this app to work with the desktop client. I will tag this as an enhancement (because it really is still an open issue). I guess a whitelisting only for the api/info will get stuck after the desktop client reaches out for the rest of the api to communicate - but I guess we will have to look into that too.

**Comment by liebeimquadrat** [comment]
hey, is there any way to use rocket chat with the desktop client?

**Comment by arthurzenika** [comment]
@liebeimquadrat haven't found a way to make it work (yet). Maybe a separate domain is a prerequisite ? I'm not sure when or how the "SSO has been disabled" (cf @selamanse 's comment) and if that fixes it.
