### ISSUE TITLE
Unable to Login into Rocketchat

### ISSUE THREAD

**Issue by workbykiran** [YunoHost-Apps/rocketchat_ynh#43]
Hi,

I successfully deployed Rocket chat from yunohost administration interface. however when logged into yunohost with a user and then opened rocket chat, then:
1. It is asking to authenticate by displaying login page.
2. Even if i manually key in the username and password, i was not able to login at all.

Iam using latest yunohost and rocket chat as deployed couple of days back. 

Will there be any default login credentials to login into Rocket chat for the first time to do any specific configuration?

**Comment by selamanse** [comment]
Hi @workbykiran,

first off: thanks for using this package and giving feedback. It helps to improve if we get scenarios of how it is being used.

This rocketchat package for yunohost currently does not support sso. So you have to reenter credentials at the rocketchat login page (using your yunohost user and yunohost password).
Currently the easiest way to use rocketchat for yunohost is to install it as a public app (so without sso protection), so that you do not have to login twice, and also are able to use it with the desktop or mobile app. (see also issue #41 ).

If your problem persists please give me some details about your installation so I may further investigate.

**Comment by workbykiran** [comment]
Thanks for the information. However iam not able to login with the same credentials which i used to login yunohost. Can you tell me where the logs are available for the rocketchat login failures. I dont see in /var/log folder.

**Comment by selamanse** [comment]
Hi @workbykiran, logs are not stored in any file at the moment but in the journalctl system. Please try `journalctl -u rocketchat -r` on your system for logs of the rocketchat service.

**Comment by krishna-kashyap** [comment]
I could see a No such object error from LDAP module in the journalctl. Not sure which LDAP config is causing this

**Comment by selamanse** [comment]
@workbykiran @krishna-kashyap I have updated this package. can you please upgrade and reopen if your issues still exists? thank you.
